(() => {
  const service=document.querySelector('#home-booking-service'),calendar=document.querySelector('#home-booking-calendar'),monthTitle=document.querySelector('#home-booking-month'),selectedLabel=document.querySelector('#home-booking-selected'),durationLabel=document.querySelector('#home-booking-duration'),slots=document.querySelector('#home-booking-slots'),message=document.querySelector('#home-booking-message'),continueBtn=document.querySelector('#home-booking-continue');
  if(!service||!calendar)return;
  const API='http://127.0.0.1:8000',durations={'Dépannage':'1 h','Installation électrique':'2 h','Rénovation électrique':'4 h','Mise en conformité':'2 h','Borne de recharge':'2 h','Autre':'1 h'};
  const today=new Date();today.setHours(0,0,0,0);let view=new Date(today.getFullYear(),today.getMonth(),1),selected=null,selectedTime=null;
  const pad=n=>String(n).padStart(2,'0'),iso=d=>d.getFullYear()+'-'+pad(d.getMonth()+1)+'-'+pad(d.getDate()),pretty=s=>new Intl.DateTimeFormat('fr-FR',{weekday:'long',day:'numeric',month:'long'}).format(new Date(s+'T12:00:00'));
  const setMessage=(t,e=false)=>{message.textContent=t;message.classList.toggle('error',e)};
  function render(){monthTitle.textContent=new Intl.DateTimeFormat('fr-FR',{month:'long',year:'numeric'}).format(view);calendar.innerHTML='';const first=(view.getDay()+6)%7,last=new Date(view.getFullYear(),view.getMonth()+1,0).getDate();for(let i=0;i<first;i++)calendar.appendChild(document.createElement('span'));for(let n=1;n<=last;n++){const d=new Date(view.getFullYear(),view.getMonth(),n),key=iso(d),b=document.createElement('button');b.type='button';b.textContent=n;if(d<today)b.disabled=true;if(d.getTime()===today.getTime())b.classList.add('today');if(selected===key)b.classList.add('selected');b.addEventListener('click',()=>selectDate(key));calendar.appendChild(b)}}
  async function loadSlots(){if(!selected){slots.textContent='Sélectionnez une date.';return}if(!service.value){slots.textContent='Choisissez d’abord le type d’intervention.';return}slots.textContent='Chargement…';selectedTime=null;continueBtn.classList.add('disabled');try{const response=await fetch(API+'/api/slots?date='+encodeURIComponent(selected)+'&service='+encodeURIComponent(service.value));const data=await response.json();if(!response.ok)throw new Error(data.error||'Le serveur est indisponible.');slots.innerHTML='';if(!data.slots?.length){slots.textContent='Aucun créneau disponible pour cette date.';return}data.slots.forEach(value=>{const b=document.createElement('button');b.type='button';b.className='booking-home-slot';b.textContent=value;b.addEventListener('click',()=>{document.querySelectorAll('.booking-home-slot').forEach(x=>x.classList.remove('selected'));b.classList.add('selected');selectedTime=value;continueBtn.classList.remove('disabled');continueBtn.href='reservation.html?date='+encodeURIComponent(selected)+'&service='+encodeURIComponent(service.value)+'&time='+encodeURIComponent(value);setMessage('Créneau sélectionné : '+value+'.')});slots.appendChild(b)})}catch(e){slots.textContent='Impossible de charger les disponibilités.';setMessage(e.message||'Serveur inaccessible.',true)}}
  function selectDate(key){selected=key;selectedLabel.textContent=pretty(key);selectedTime=null;continueBtn.classList.add('disabled');continueBtn.href='reservation.html';setMessage('');render();loadSlots()}
  service.addEventListener('change',()=>{durationLabel.textContent=durations[service.value]||'—';if(selected)loadSlots()});
  document.querySelector('#home-booking-prev').addEventListener('click',()=>{const p=new Date(view.getFullYear(),view.getMonth()-1,1),m=new Date(today.getFullYear(),today.getMonth(),1);if(p>=m){view=p;render()}});
  document.querySelector('#home-booking-next').addEventListener('click',()=>{view=new Date(view.getFullYear(),view.getMonth()+1,1);render()});
  render();
})();