(() => {
  const service=document.querySelector('#home-booking-service'),calendar=document.querySelector('#home-booking-calendar'),monthTitle=document.querySelector('#home-booking-month'),selectedLabel=document.querySelector('#home-booking-selected'),durationLabel=document.querySelector('#home-booking-duration'),slots=document.querySelector('#home-booking-slots'),message=document.querySelector('#home-booking-message'),form=document.querySelector('#home-booking-form'),confirmBtn=document.querySelector('#home-booking-confirm');
  if(!service||!calendar||!form)return;
  const API='http://127.0.0.1:8000',durations={'Dépannage':'1 h','Installation électrique':'2 h','Rénovation électrique':'4 h','Mise en conformité':'2 h','Borne de recharge':'2 h','Autre':'1 h'};
  const today=new Date();today.setHours(0,0,0,0);let view=new Date(today.getFullYear(),today.getMonth(),1),selected=null,selectedTime=null;
  const pad=n=>String(n).padStart(2,'0'),iso=d=>d.getFullYear()+'-'+pad(d.getMonth()+1)+'-'+pad(d.getDate()),pretty=s=>new Intl.DateTimeFormat('fr-FR',{weekday:'long',day:'numeric',month:'long'}).format(new Date(s+'T12:00:00'));
  const setMessage=(t,e=false)=>{message.textContent=t;message.classList.toggle('error',e)};
  function updateButton(){confirmBtn.classList.toggle('disabled',!(selected&&selectedTime&&service.value))}
  function render(){monthTitle.textContent=new Intl.DateTimeFormat('fr-FR',{month:'long',year:'numeric'}).format(view);calendar.innerHTML='';const first=(view.getDay()+6)%7,last=new Date(view.getFullYear(),view.getMonth()+1,0).getDate();for(let i=0;i<first;i++)calendar.appendChild(document.createElement('span'));for(let n=1;n<=last;n++){const d=new Date(view.getFullYear(),view.getMonth(),n),key=iso(d),b=document.createElement('button');b.type='button';b.textContent=n;if(d<today)b.disabled=true;if(d.getTime()===today.getTime())b.classList.add('today');if(selected===key)b.classList.add('selected');b.addEventListener('click',()=>selectDate(key));calendar.appendChild(b)}}
  async function loadSlots(){if(!selected){slots.textContent='Sélectionnez une date.';return}if(!service.value){slots.textContent='Choisissez d’abord le type d’intervention.';updateButton();return}slots.textContent='Chargement…';selectedTime=null;updateButton();try{const r=await fetch(API+'/api/slots?date='+encodeURIComponent(selected)+'&service='+encodeURIComponent(service.value));const x=await r.json();if(!r.ok)throw new Error(x.error||'Le serveur est indisponible.');slots.innerHTML='';if(!x.slots?.length){slots.textContent='Aucun créneau disponible pour cette date.';return}x.slots.forEach(v=>{const b=document.createElement('button');b.type='button';b.className='booking-home-slot';b.textContent=v;b.addEventListener('click',()=>{document.querySelectorAll('.booking-home-slot').forEach(y=>y.classList.remove('selected'));b.classList.add('selected');selectedTime=v;updateButton();setMessage('Créneau sélectionné : '+v+'.')});slots.appendChild(b)})}catch(e){slots.textContent='Impossible de charger les disponibilités.';setMessage(e.message||'Serveur inaccessible.',true)}}
  function selectDate(key){selected=key;selectedLabel.textContent=pretty(key);setMessage('');render();loadSlots()}
  service.addEventListener('change',()=>{durationLabel.textContent=durations[service.value]||'—';loadSlots()});
  document.querySelector('#home-booking-prev').addEventListener('click',()=>{const p=new Date(view.getFullYear(),view.getMonth()-1,1),m=new Date(today.getFullYear(),today.getMonth(),1);if(p>=m){view=p;render()}});
  document.querySelector('#home-booking-next').addEventListener('click',()=>{view=new Date(view.getFullYear(),view.getMonth()+1,1);render()});
  form.addEventListener('submit',async e=>{e.preventDefault();setMessage('');if(!service.value){setMessage('Choisissez d’abord le type d’intervention.',true);return}if(!selected||!selectedTime){setMessage('Choisissez une date et un horaire.',true);return}const payload={service:service.value,date:selected,time:selectedTime,name:document.querySelector('#home-booking-name').value.trim(),phone:document.querySelector('#home-booking-phone').value.trim(),email:document.querySelector('#home-booking-email').value.trim(),notes:document.querySelector('#home-booking-notes').value.trim()};if(!payload.name||!payload.phone){setMessage('Le nom et le téléphone sont obligatoires.',true);return}confirmBtn.disabled=true;confirmBtn.classList.add('disabled');confirmBtn.querySelector('span').textContent='…';try{const r=await fetch(API+'/api/bookings',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(payload)}),x=await r.json();if(!r.ok)throw new Error(x.error||'Le serveur a refusé la réservation.');setMessage('✓ Rendez-vous confirmé pour '+pretty(selected)+' à '+selectedTime+'. Nous avons bien reçu votre demande.');form.reset();selected=null;selectedTime=null;durationLabel.textContent='—';selectedLabel.textContent='Choisissez une date';slots.textContent='Sélectionnez une date.';render()}catch(e){setMessage(e.message||'Une erreur est survenue.',true)}finally{confirmBtn.disabled=false;confirmBtn.querySelector('span').textContent='→';updateButton()}});
  render();updateButton();
})();